DOMAIN ?= AF_INET
SERVER ?= localhost
PATH_TYPE ?= curved
LABEL ?= PID_Kp2.0_Ki0.1_Kd0.5_curved_noise0.05_run1

all: build sim
compile:
	@echo "No compile needed"
build:
	@echo "No build needed"
sim:
	cd /home/ubuntu/capstone_ali/ali_hatem && PYTHONPATH=. python3 src/visualizer/visualizer.py --domain=$(DOMAIN) --server-url=$(SERVER) --label=$(LABEL) --path=$(PATH_TYPE); bash
clean:
	@echo "Nothing to clean"
